services:
  postgres:
    image: postgres:15
    container_name: schooler_postgres
    env_file:
      - .env
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-user}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
      POSTGRES_DB: ${DB_NAME:-schooler_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: ["postgres", "-c", "max_connections=200"]
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${DB_USER:-user} -d ${DB_NAME:-schooler_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  fastapi:
    env_file:
      - .env
    volumes:
      - ./:/app
    image: schooler_fastapi:latest
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: schooler_fastapi
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      DB_USER: ${DB_USER:-user}
      DB_PASS: ${DB_PASS:-password}
      DB_HOST: ${DB_HOST:-schooler_postgres}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-schooler_db}
      UVICORN_APPS: main:app
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local
